test:
  # MySQL test database
  services:
    - mysql:5.7
  variables:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: next
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: homemission

  image: node:16.11
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  stage: test
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run test:ci
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
