test:
  # MySQL test database
  services:
    - mysql:5.7
  variables:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: next
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: homemission

  image: node:16.11
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .npm/
  stage: test
  script:
    - npm ci
    - npm run test:ci
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
