version: '3'
services:
  ### Database ###
  database:
    image: mysql:5.7
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE}
    volumes:
      - database:/var/lib/mysql

### Volumes ###
volumes:
  database:
    driver: local
