version: '3'
services:
  ### Database ###
  database-prod:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE}
    volumes:
      - database-prod:/var/lib/mysql

  wg-organisierspiel:
    image: registry.code.fbi.h-da.de/isttomare/wg-organisierspiel
    ports:
      - 80:80
    env_file:
      - .env.local
    environment:
      DATABASE_HOST: database-prod
    depends_on:
      - database-prod

### Volumes ###
volumes:
  database-prod:
    driver: local
